### ISSUE TITLE
open_gapps-arm-4.4-XXX can't work on CM11

### ISSUE THREAD

**Issue by dna1982** [opengapps/opengapps#19]
Device: Nexus 7 2013 WIFI(Flo)
Rom: cm-11-20141115-SNAPSHOT-M12-flo
Kernel: ElementalX-N7-2.15-cm

open_gapps-arm-4.4-XXX doesn't work on CM11. After first reboot, while executing the setup wizard, I get a FC and can't continue...
Here is the exception message from Logcat:
06-10 07:39:40.315  23240-23240/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.google.android.setupwizard, PID: 23240
    java.lang.NoSuchMethodError: android.net.wifi.IWifiManager.setWifiEnabled
            at com.google.android.setupwizard.BaseActivity.tryEnablingWifi(BaseActivity.java:1526)
            at com.google.android.setupwizard.WelcomeActivity$2.run(WelcomeActivity.java:129)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mfonville** [comment]
Sorry, I am not able to help with this one, the source of the problem is within your ROM, where the java.lang.NoSuchMethodError: android.net.wifi.IWifiManager.setWifiEnabled method has been changed (if you google this line, you will get a lot of results concerning this issue)
