### ISSUE TITLE
permission issue on cm13/nano - fix it pleas as every time i install gapps i need disable Setup Wizard after install 

### ISSUE THREAD

**Issue by c3ph3us** [opengapps/opengapps#228]
01-20 05:04:33.397 4753-4753/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/system@priv-app@SetupWizard@SetupWizard.apk@classes.dex: Permission denied
01-20 05:04:33.569 4740-4740/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.google.android.setupwizard, PID: 4740
                                                 java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication: java.lang.SecurityException: addOnSubscriptionsChangedListener: Neither user 10065 nor current process has android.permission.READ_PHONE_STATE.
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4759)
                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5470)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.SecurityException: addOnSubscriptionsChangedListener: Neither user 10065 nor current process has android.permission.READ_PHONE_STATE.
                                                     at android.os.Parcel.readException(Parcel.java:1637)
                                                     at android.os.Parcel.readException(Parcel.java:1590)
                                                     at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.addOnSubscriptionsChangedListener(ITelephonyRegistry.java:500)
                                                     at android.telephony.SubscriptionManager.addOnSubscriptionsChangedListener(SubscriptionManager.java:457)
                                                     at com.google.android.setupwizard.carrier.PhoneMonitor.<init>(PhoneMonitor.java:509)
                                                     at com.google.android.setupwizard.carrier.PhoneMonitor.initInstance(PhoneMonitor.java:70)
                                                     at com.google.android.setupwizard.SetupWizardApplication.onCreate(SetupWizardApplication.java:27)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4756)
                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5470) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mfonville** [comment]
a) You need to first request support for any problems your experience on the XDA Forum as stated in the FAQ
b) Your ROM just misses the permission patches necessary: https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0
c) You just opened 3(!!!!!) issues for this nonsense while in the FAQ it is clearly stated that directly opening any GitHub bugreports is NOT appreciated.

**Comment by c3ph3us** [comment]
1. i don't use xda 
2. my rom is nightly cm13 :) 
3. "GitHub bugreports is NOT appreciated. " see first &/ DISABLE ISSUES ON GITHUB :) 

one user of open gapps  less 
THX

**Comment by c3ph3us** [comment]
from: https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0
"To install Open GApps on 6.0 your ROM needs the following patch to prevent Force Closures at first boot: https://github.com/TeamExodus/frameworks_base/commit/9c36be651e83fb039a262682839bd920b033007a

**This patch is included by default in Cyanogenmod sources**, but not in AOSP."

# These are total bulshit!!!

see: http://review.cyanogenmod.org/#/c/116418   Code-Review -2 (Abandoned)
