### ISSUE TITLE
location issue on nano 6.1- 20.01

### ISSUE THREAD

**Issue by c3ph3us** [opengapps/opengapps#229]
01-20 05:28:04.357 7545-7565/? E/LocationManagerCompat: Unable to assign LocationManager blame through WorkSource
                                                        java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
                                                            at android.os.Parcel.readException(Parcel.java:1637)
                                                            at android.os.Parcel.readException(Parcel.java:1590)
                                                            at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
                                                            at android.location.LocationManager.requestLocationUpdates(LocationManager.java:892)
                                                            at android.location.LocationManager.requestLocationUpdates(LocationManager.java:839)
                                                            at com.google.android.location.util.af.a(SourceFile:40)
                                                            at com.google.android.location.fused.a.o.a(SourceFile:40)
                                                            at com.google.android.location.fused.a.p.g(SourceFile:56)
                                                            at com.google.android.location.fused.a.p.ac_(SourceFile:37)
                                                            at com.google.android.location.fused.ay.a(SourceFile:318)
                                                            at com.google.android.location.fused.k.a(SourceFile:207)
                                                            at com.google.android.location.fused.f.a(SourceFile:164)
                                                            at com.google.android.location.fused.f.a(SourceFile:73)
                                                            at com.google.android.location.fused.bj.a(SourceFile:170)
                                                            at com.google.android.location.fused.dh.a(SourceFile:151)
                                                            at com.google.android.location.fused.cm.a(SourceFile:60)
                                                            at com.google.android.location.fused.co.a(SourceFile:126)
                                                            at com.google.android.location.fused.dl.handleMessage(SourceFile:94)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at com.google.android.location.util.au.dispatchMessage(SourceFile:50)
                                                            at android.os.Looper.loop(Looper.java:148)
                                                            at android.os.HandlerThread.run(HandlerThread.java:61)

01-20 05:33:26.747 8520-8547/? E/AndroidRuntime: FATAL EXCEPTION: NetworkLocationCallbackRunner
                                                 Process: com.google.android.gms.persistent, PID: 8520
                                                 java.lang.SecurityException: Neither user 1010064 nor current process has android.permission.ACCESS_COARSE_LOCATION.
                                                     at android.os.Parcel.readException(Parcel.java:1637)
                                                     at android.os.Parcel.readException(Parcel.java:1590)
                                                     at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:553)
                                                     at android.telephony.TelephonyManager.listen(TelephonyManager.java:2760)
                                                     at com.google.android.location.os.real.ac.handleMessage(SourceFile:239)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by mfonville** [comment]
a) You need to first request support for any problems your experience on the XDA Forum as stated in the FAQ
b) Your ROM just misses the permission patches necessary: https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0
c) You just opened 3(!!!!!) issues for this nonsense while in the FAQ it is clearly stated that directly opening any GitHub bugreports is NOT appreciated.

**Comment by c3ph3us** [comment]
Process: com.google.android.gms.persistent, PID: 8520
java.lang.SecurityException: Neither user 1010064 nor current process has android.permission.ACCESS_COARSE_LOCATION.

its yours appS CRASHING - I DON'T WANT GMS   - TO USE LOCATION (ANY) - ITS OFF ON MY DEVICE U SHOULD RESPECT THAT - FOR THAT PERMISSIONS WERE MADE

**Comment by xtrm0** [comment]
"c) You just opened 3(!!!!!) issues for this nonsense while in the FAQ it is clearly stated that directly opening any GitHub bugreports is NOT appreciated" 
You can use an outside bug report system if you wan't bug reports to be private, or use the public one with tags only on the bug reports you agree with. No need to rage.
Also this seems like a legit bug report, even though the initial post doens't explains much. You could create issue guidelines to help users know what they should post instead of yelling at them to read a FAQ before posting an issue.

**Comment by xtrm0** [comment]
@mfonville

**Comment by c3ph3us** [comment]
"All apps are untouched, we do not change or modify Googles' applications but deliver them as-is"

THIS SHOULD BE ON MAIN README or any github project page (example on wiki) - not on separate server side like xda why ?

 if u decide host here project then u should maintain consistency in your actions for 
- clarines of project 
- save of time (on issue like this) 

keep in mind that delocalizing resources could be painful for end user from various points eg is here (www server availability - i think the explanation  here is unnecessary)

last of all - are u including signed apk from google or you build them and signing with own key from open source??? (if signed apk i have no reason to be here - if not - by building apk's  you are responsible as owner of opengapps  (excluding law / ownership / code license)) for any issues that involves source code.


"@mfonvillemfonville changed the title from location issue on nano 6.1- 20.01 to c3ph3us lacks the understanding that gms is written by Google, can' t read the FAQ, can't comprehend any answer and childishly insults unpaid open source developers instead, wasting their time. 2 days ago"

btw - where are the insults about u are talking ???

**Comment by bgiesing** [comment]
@c3ph3us All apps are using Google's signature and we verify it's Google's before allowing it to be published. This "bug" is with Google Play services and has NOTHING to do with us as it's an issue with Google's code.

We don't modify anything! All we do is make the scripts that automate making the zip file containing the signed Google apks.

Plus that message that you say should be on the wiki/readme. XDA is our main place so that's where it's at.

He explained it easily:
1. This is not a bug with OpenGApps so it should not be discussed on GitHub.
2. This error is due to the ROM you are using not having the correct permissions for ANY GApps package.
3. You opened 3 seperate issues for the same bug that isn't us but Google/ROMs.

Also, you don't want GMS to use location? Well, then don't install GApps as GMS is required and it always has to have that. You have to use no Google apps or services at all.

**Comment by c3ph3us** [comment]
# all welcome to see this:
https://github.com/opengapps/opengapps/issues/228#issuecomment-174248327

**Comment by abma** [comment]
i ran into the same issue, a factory reset fixed it for me.
