### ISSUE TITLE
car service & location & other - issue nano 6.1 - 20.01

### ISSUE THREAD

**Issue by c3ph3us** [opengapps/opengapps#230]
01-20 05:28:04.360 7545-7565/? E/AndroidRuntime: FATAL EXCEPTION: FlpThread
                                                 Process: com.google.android.gms.persistent, PID: 7545
                                                 java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
                                                     at android.os.Parcel.readException(Parcel.java:1637)
                                                     at android.os.Parcel.readException(Parcel.java:1590)
                                                     at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:892)
                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:498)
                                                     at com.google.android.location.util.ae.a(SourceFile:65)
                                                     at com.google.android.location.util.af.a(SourceFile:45)
                                                     at com.google.android.location.fused.a.o.a(SourceFile:40)
                                                     at com.google.android.location.fused.a.p.g(SourceFile:56)
                                                     at com.google.android.location.fused.a.p.ac_(SourceFile:37)
                                                     at com.google.android.location.fused.ay.a(SourceFile:318)
                                                     at com.google.android.location.fused.k.a(SourceFile:207)
                                                     at com.google.android.location.fused.f.a(SourceFile:164)
                                                     at com.google.android.location.fused.f.a(SourceFile:73)
                                                     at com.google.android.location.fused.bj.a(SourceFile:170)
                                                     at com.google.android.location.fused.dh.a(SourceFile:151)
                                                     at com.google.android.location.fused.cm.a(SourceFile:60)
                                                     at com.google.android.location.fused.co.a(SourceFile:126)
                                                     at com.google.android.location.fused.dl.handleMessage(SourceFile:94)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at com.google.android.location.util.au.dispatchMessage(SourceFile:50)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
01-20 05:28:06.244 7520-7520/? E/ActivityThread: Service com.google.android.gms.car.CarService has leaked ServiceConnection com.google.android.gms.car.hr@3a6129e that was originally bound here
                                                 android.app.ServiceConnectionLeaked: Service com.google.android.gms.car.CarService has leaked ServiceConnection com.google.android.gms.car.hr@3a6129e that was originally bound here
                                                     at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1093)
                                                     at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:987)
                                                     at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1315)
                                                     at android.app.ContextImpl.bindService(ContextImpl.java:1298)
                                                     at android.content.ContextWrapper.bindService(ContextWrapper.java:610)
                                                     at android.content.ContextWrapper.bindService(ContextWrapper.java:610)
                                                     at android.content.ContextWrapper.bindService(ContextWrapper.java:610)
                                                     at com.google.android.gms.common.stats.g.a(SourceFile:128)
                                                     at com.google.android.gms.common.stats.g.a(SourceFile:145)
                                                     at com.google.android.gms.car.hc.<init>(SourceFile:319)
                                                     at com.google.android.gms.car.CarChimeraService.onCreate(SourceFile:74)
                                                     at com.google.android.chimera.ServiceProxy.setImpl(SourceFile:115)
                                                     at com.google.android.chimera.ServiceProxy.onCreate(SourceFile:105)
                                                     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2921)
                                                     at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5470)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-20 05:28:06.270 7520-7520/? E/ActivityThread: Service com.google.android.gms.car.CarCallService has leaked ServiceConnection com.google.android.gms.car.dq@daafa11 that was originally bound here
                                                 android.app.ServiceConnectionLeaked: Service com.google.android.gms.car.CarCallService has leaked ServiceConnection com.google.android.gms.car.dq@daafa11 that was originally bound here
                                                     at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1093)
                                                     at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:987)
                                                     at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1315)
                                                     at android.app.ContextImpl.bindService(ContextImpl.java:1298)
                                                     at android.content.ContextWrapper.bindService(ContextWrapper.java:610)
                                                     at com.google.android.gms.common.stats.g.a(SourceFile:128)
                                                     at com.google.android.gms.common.stats.g.a(SourceFile:145)
                                                     at com.google.android.gms.car.dp.a(SourceFile:586)
                                                     at com.google.android.gms.car.dp.<init>(SourceFile:511)
                                                     at com.google.android.gms.car.dp.a(SourceFile:488)
                                                     at com.google.android.gms.car.dm.<init>(SourceFile:112)
                                                     at com.google.android.gms.car.CarCallService.onBind(SourceFile:79)
                                                     at android.app.ActivityThread.handleBindService(ActivityThread.java:2948)
                                                     at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1451)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5470)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by c3ph3us** [comment]
01-20 05:26:55.226 6202-7113/? E/DynamiteModule: Failed to load IDynamiteLoader from GmsCore
                                                 java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.chimera.container.DynamiteLoaderImpl" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk"],nativeLibraryDirectories=[/data/user/10/com.google.android.gms/app_extracted_libs/armeabi-v7a, /system/priv-app/PrebuiltGmsCore/lib/arm, /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at com.google.android.gms.dynamite.a.a(SourceFile:212)
                                                     at com.google.android.gms.dynamite.a.a(SourceFile:169)
                                                     at com.google.android.gms.dynamite.a.a(SourceFile:122)
                                                     at com.google.android.gms.flags.a.a.a(SourceFile:58)
                                                     at com.google.android.gms.flags.h.a(SourceFile:16)
                                                     at com.google.android.gms.init.InitializeIntentService.onHandleIntent(SourceFile:93)
                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.chimera.container.DynamiteLoaderImpl
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                     		... 11 more
                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by mfonville** [comment]
a) You need to first request support for any problems your experience on the XDA Forum as stated in the FAQ
b) Your ROM just misses the permission patches necessary: https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0
c) You just opened 3(!!!!!) issues for this nonsense while in the FAQ it is clearly stated that directly opening any GitHub bugreports is NOT appreciated.

**Comment by c3ph3us** [comment]
related https://github.com/opengapps/opengapps/issues/228#issuecomment-174248327
