### ISSUE TITLE
Request: Option to keep the AOSP Dialer when Google Dialer is installed.

### ISSUE THREAD

**Issue by VincentJoshuaET** [opengapps/opengapps#618]
This fixes the partially broken emergency calls on Lineage OS.

**Comment by rcmaehl** [comment]
If by "Partially broken" you mean Completely Denies access to Emergency calls as it crashes Android and by "Lineage OS" you mean most if not all Cyanogenmod based ROMs.

**Comment by vwvtkxjobkvpqszygxmjvgaavwvfju** [comment]
I can't find a huge warning about this anywhere on the website. Is this being worked on or not? It's a critical bug.

**Comment by rcmaehl** [comment]
LineageOS team is working on making it fail gracefully https://review.lineageos.org/c/LineageOS/android_packages_services_Telephony/+/209045 at the very least

**Comment by viggy96** [comment]
@rcmaehl I just legally test called 911, and while the call does go through fine on the Google Dialer, it does not show the proper in-call screen, the Dialer app just freezes. The phone does not reboot or crash. The call remains connected however.

**Comment by VincentJoshuaET** [comment]
@viggy96 That doesn't happen when both Dialer apps are installed. That's the reason why I'm requesting above 

_Sent from my ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jamuir** [comment]
I have similar issues with Google Dialer (18.0.187698947) on oreo (8.0).

When I initiate a call, Google Dialer crashes immediately, but the call connects normally, just without any in-call ui.

Relevant logcat follows:

```
04-26 20:39:04.783 W/Bundle  (21340): u0 : Key com.android.dialer.callintent.CALL_SPECIFIC_APP_DATA expected Bundle but value was a [B.  The default value <null> was returned.
04-26 20:39:04.784 W/Bundle  (21340): u0 : Attempt to cast generated internal exception:
04-26 20:39:04.784 W/Bundle  (21340): java.lang.ClassCastException: byte[] cannot be cast to android.os.Bundle
04-26 20:39:04.784 W/Bundle  (21340):   at android.os.Bundle.getBundle(Bundle.java:871)
04-26 20:39:04.784 W/Bundle  (21340):   at com.android.dialer.callintent.CallIntentParser.getCallSpecificAppData(CallIntentParser.java:39)
04-26 20:39:04.784 W/Bundle  (21340):   at com.android.incallui.call.DialerCall.parseCallSpecificAppData(DialerCall.java:848)
04-26 20:39:04.784 W/Bundle  (21340):   at com.android.incallui.call.DialerCall.<init>(DialerCall.java:294)
04-26 20:39:04.784 W/Bundle  (21340):   at com.android.incallui.call.CallList.onCallAdded(CallList.java:116)
04-26 20:39:04.784 W/Bundle  (21340):   at com.android.incallui.InCallPresenter.onCallAdded(InCallPresenter.java:512)
04-26 20:39:04.784 W/Bundle  (21340):   at com.android.incallui.InCallServiceImpl.onCallAdded(InCallServiceImpl.java:51)
04-26 20:39:04.784 W/Bundle  (21340):   at android.telecom.InCallService$2.onCallAdded(InCallService.java:248)
04-26 20:39:04.784 W/Bundle  (21340):   at android.telecom.Phone.fireCallAdded(Phone.java:346)
04-26 20:39:04.784 W/Bundle  (21340):   at android.telecom.Phone.internalAddCall(Phone.java:148)
04-26 20:39:04.784 W/Bundle  (21340):   at android.telecom.InCallService$1.handleMessage(InCallService.java:99)
04-26 20:39:04.784 W/Bundle  (21340):   at android.os.Handler.dispatchMessage(Handler.java:105)
04-26 20:39:04.784 W/Bundle  (21340):   at android.os.Looper.loop(Looper.java:164)
04-26 20:39:04.784 W/Bundle  (21340):   at android.app.ActivityThread.main(ActivityThread.java:6541)
04-26 20:39:04.784 W/Bundle  (21340):   at java.lang.reflect.Method.invoke(Native Method)
04-26 20:39:04.784 W/Bundle  (21340):   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
04-26 20:39:04.784 W/Bundle  (21340):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
04-26 20:39:04.784 D/AndroidRuntime(21340): Shutting down VM
--------- beginning of crash
04-26 20:39:04.784 E/AndroidRuntime(21340): FATAL EXCEPTION: main
04-26 20:39:04.784 E/AndroidRuntime(21340): Process: com.android.dialer, PID: 21340
04-26 20:39:04.784 E/AndroidRuntime(21340): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.dialer.protos.ProtoParsers.get(ProtoParsers.java:40)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.dialer.protos.ProtoParsers.getTrusted(ProtoParsers.java:52)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.dialer.callintent.CallIntentParser.getCallSpecificAppData(CallIntentParser.java:38)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.incallui.call.DialerCall.parseCallSpecificAppData(DialerCall.java:848)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.incallui.call.DialerCall.<init>(DialerCall.java:294)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.incallui.call.CallList.onCallAdded(CallList.java:116)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.incallui.InCallPresenter.onCallAdded(InCallPresenter.java:512)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.incallui.InCallServiceImpl.onCallAdded(InCallServiceImpl.java:51)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at android.telecom.InCallService$2.onCallAdded(InCallService.java:248)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at android.telecom.Phone.fireCallAdded(Phone.java:346)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at android.telecom.Phone.internalAddCall(Phone.java:148)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at android.telecom.InCallService$1.handleMessage(InCallService.java:99)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at android.os.Handler.dispatchMessage(Handler.java:105)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at android.os.Looper.loop(Looper.java:164)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at android.app.ActivityThread.main(ActivityThread.java:6541)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at java.lang.reflect.Method.invoke(Native Method)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
04-26 20:39:04.784 E/AndroidRuntime(21340):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
04-26 20:39:04.787 W/ActivityManager( 1000): u0 :   Force finishing activity com.android.dialer/com.android.incallui.InCallActivity
04-26 20:39:04.789 W/ActivityManager( 1000): u0 :   Force finishing activity com.google.android.dialer/.extensions.GoogleDialtactsActivity
04-26 20:39:04.796 I/ActivityManager( 1000): u0 : Killing 23041:com.android.providers.calendar/u0a2 (adj 906): empty #17
```

**Comment by NicholasBuse** [comment]
Is anyone on this thread (or aware of the issue in general) knowledgeable of the differences between the two flavors of dialer out there now?

For Google Phone 18.0.187698947 for the same arch/dpi, there are two APKs (One is ~10MB bigger and has the feature: uses-feature: name='com.google.android.feature.PIXEL_2017_EXPERIENCE')

[Google Phone 18.0.187698947 (arm) (480dpi) (Android 6.0+)](https://www.apkmirror.com/apk/google-inc/google-phone/google-phone-18-0-187698947-release/google-phone-18-0-187698947-android-apk-download/)
[Google Phone 18.0.187698947 (arm) (480dpi) (Android 6.0+) {PIXEL}](https://www.apkmirror.com/apk/google-inc/google-phone/google-phone-18-0-187698947-release/google-phone-18-0-187698947-12-android-apk-download/)

The PIXEL ones take precedence in the OpenGApps build space since they have higher VersionCodes...

I wonder if I do a test build with no PIXEL variants if the issue would be addressed?
Thoughts?
Takers (and what arch/build variant do you want)?

**Comment by NicholasBuse** [comment]
I have build (and uploads are in progress) 4 zips with NO PIXEL Google Phones:
1. [arm 8.0 stock](https://www.androidfilehost.com/?fid=746010030569971368)
2. [arm 8.1 stock](https://www.androidfilehost.com/?fid=890129502657600307)
3. arm64 8.0 stock
4. arm64 8.1 stock

Find them here: https://www.androidfilehost.com/?w=files&flid=253259

**Comment by viggy96** [comment]
@NicholasBuse, sorry, what was the significance of these builds?

**Comment by NicholasBuse** [comment]
@viggy96 , these 4 builds do not have any Google Phone APKs that are for the feature PIXEL_2017_EXPERIENCE...

**Comment by jamuir** [comment]
I tested four of the apks in the dropbox folder (61, 60, 59, 52) via "adb install" and hit an issue with each one.  And the result was the same when I installed from the play store.

I see that all the apks in the dropbox folder contain the string PIXEL_2017_EXPERIENCE.  Is that expected?

```
$ strings --print-file-name com.google.android.dialer-*.apk | grep PIXEL_20
com.google.android.dialer-2443252.apk: 0com.google.android.feature.PIXEL_2017_EXPERIENCE
com.google.android.dialer-2443253.apk: 0com.google.android.feature.PIXEL_2017_EXPERIENCE
com.google.android.dialer-2443254.apk: 0com.google.android.feature.PIXEL_2017_EXPERIENCE
com.google.android.dialer-2443256.apk: 0com.google.android.feature.PIXEL_2017_EXPERIENCE
com.google.android.dialer-2443259.apk: 0com.google.android.feature.PIXEL_2017_EXPERIENCE
com.google.android.dialer-2443260.apk: 0com.google.android.feature.PIXEL_2017_EXPERIENCE
com.google.android.dialer-2443261.apk: 0com.google.android.feature.PIXEL_2017_EXPERIENCE
```

**Comment by NicholasBuse** [comment]
```sh
aapt dump badging [apk] | grep PIXEL
```

**Comment by jamuir** [comment]
Thanks for the `aapt` command.  I confirm that there are no grep hits when I use `aapt dump badging ...` on those apks.

Playstore verion is 18.0.187698947.

![sc-10](https://user-images.githubusercontent.com/5332385/39401761-52b55cfa-4b1b-11e8-8e8e-d8d0e6372ae0.png)

**Comment by jamuir** [comment]
After looking at the logcat output more carefully, I see that the crash is actually in AOSP Dialer (`com.android.dialer`), not Google Dialer (`com.google.android.dialer`) (i.e. even though the call is initiated by Google Dialer, it is AOSP Dialer that crashes).

If I disable AOSP Dialer, then Google Dialer works fine:

```
# pm disable com.android.dialer
Package com.android.dialer new state: disabled
```

I'm not sure if there is anything in the opengapps package that needs to be "fixed" here.  Whether or not the installation script should disable AOSP Dialer to avoid this problem isn't clear to me.

**Comment by VincentJoshuaET** [comment]
Two scenarios:

When Google Dialer is installed and the AOSP Dialer is removed (the default behavior of stock GApps and higher), calling emergency numbers will not show the In Call UI.

When Google Dialer is not installed with Open GApps and the AOSP Dialer is retained, and you install Google Dialer from the Google Play Store or by sideloading, calling emergency numbers will show the In Call UI.

The calls themselves still work in both scenarios.

**Comment by viggy96** [comment]
I still to flash the Google Dialer, since I personally like the dialer to be a system app. Regardless, the flashing of the Google Dialer should not remove the AOSP dialer, since that breaks functionality. Therefore, the default behavior of the OpenGApps installers should be changed such that they don't remove the AOSP dialer when the Google Dialer is selected to be flashed.

**Comment by jamuir** [comment]
Could you guys post logcat output for the crashes you observe?  This will help us figure out exactly what component is crashing.

**Comment by viggy96** [comment]
That's not exactly something we can 'just do', since that would involve calling an emergency number...

**Comment by viggy96** [comment]
As @VincentJoshuaET says, if the existing dialer app is not removed in the OpenGApps flashing process, then the Google Dialer will function properly.

**Comment by viggy96** [comment]
The AOSP dialer can even be disabled, its just that the files for that dialer still need to exist for the Google Dialer to function properly during an emergency call.

**Comment by viggy96** [comment]
So, maybe, instead of removing the AOSP dialer, OpenGApps can just disable it?

**Comment by VincentJoshuaET** [comment]
I tried disabling the AOSP Dialer, but it still caused emergency calls not to show the in call UI. I guess  the best solution is to not just do anything to the AOSP Dialer even if Google Dialer is installed.

**Comment by viggy96** [comment]
@VincentJoshuaET, do you want to do test emergency call while logging? I've already done it twice in my area, and I don't want  to do it too often...

**Comment by viggy96** [comment]
@jamuir Can we just add an option to not remove the stock dialer, just like the options to not remove the other stock apps? I feel like that would be quite simple...

**Comment by VincentJoshuaET** [comment]
@viggy96 i didn't install Google Dialer from the Open GApps, so that the AOSP one won't be removed.

_Sent from my ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jamuir** [comment]
Adding an option to control the removal of AOSP Dialer as a work-around doesn't sound too difficult, but that is just a guess; my dev changes have been limited to the project https://github.com/opengapps/aosp_build.

What is really needed is logcat output captured during the emergency call defect so that we can figure out what the real problem is.

**Comment by jamuir** [comment]
https://www.reddit.com/r/LineageOS/comments/6h0u8j/emergency_calls_911_112_impossible/

if you expand the comment thread at the bottom of that page, then you'll see some info from Lineage team members on how to test emergency dialing without actually placing a call to an emergency centre.

They suggest changing `setprop ril.test.emergencynumber ...`, but I don't have that property on my device.

What does work for me is this:

```
$ adb shell
$ su
# getprop ril.ecclist                                                                                                                                        
911,112,*911,#911
# setprop ril.ecclist $(getprop ril.ecclist),9876543210
```
Now, the emergency dialer ui will let a call to 9876543210 go through.

@VincentJoshuaET @viggy96 you could try reproducing the defect and grabbing logcat this way.

**Comment by viggy96** [comment]
[GoogleDialerError.txt](https://github.com/opengapps/opengapps/files/1968633/GoogleDialerError.txt)
Here you go guys.

**Comment by jamuir** [comment]
I see the crash:

```
05-02 15:37:03.295   968   968 E Telecom : InCallController: Package Manager could not find ComponentName: ComponentInfo{com.android.dialer/com.android.incallui.InCallServiceImpl}. Trying to bind anyway.: PCR.oR@APU
05-02 15:37:03.295   968   968 E Telecom : java.lang.Exception
05-02 15:37:03.295   968   968 E Telecom : 	at com.android.server.telecom.InCallController.getInCallServiceComponent(InCallController.java:936)
05-02 15:37:03.295   968   968 E Telecom : 	at com.android.server.telecom.InCallController.bindToServices(InCallController.java:888)
05-02 15:37:03.295   968   968 E Telecom : 	at com.android.server.telecom.InCallController.onCallAdded(InCallController.java:642)
05-02 15:37:03.295   968   968 E Telecom : 	at com.android.server.telecom.CallsManager.addCall(CallsManager.java:2079)
05-02 15:37:03.295   968   968 E Telecom : 	at com.android.server.telecom.CallsManager.startOutgoingCall(CallsManager.java:1069)
05-02 15:37:03.295   968   968 E Telecom : 	at com.android.server.telecom.CallIntentProcessor.processOutgoingCallIntent(CallIntentProcessor.java:183)
05-02 15:37:03.295   968   968 E Telecom : 	at com.android.server.telecom.CallIntentProcessor.processIntent(CallIntentProcessor.java:87)
05-02 15:37:03.295   968   968 E Telecom : 	at com.android.server.telecom.components.PrimaryCallReceiver.onReceive(PrimaryCallReceiver.java:22)
```
The system is indeed looking for a component of AOSP Dialer.


However, earlier on in that log, I also see this:

```
05-02 14:23:28.413  3260  3260 I SystemConfig: Non-xml file /system/etc/permissions/com.google.android.dialer.support.xml.syndre in /system/etc/permissions directory, ignoring
```

**Comment by viggy96** [comment]
Any update on this?

**Comment by viggy96** [comment]
Can we please just disable the removal of the AOSP dialer until further notice?

**Comment by mwyau** [comment]
Please test/comment, thanks. Tested myself with a stock install.
#639

**Comment by DavidBerdik** [comment]
Any change to this?

**Comment by benwa** [comment]
It seems that wiki page was deleted in commit `0ff3237420e05b6b5e3a11de3f3b28d3bb75d918`
Can you `git revert 0ff3237420e05b6b5e3a11de3f3b28d3bb75d918` on https://github.com/opengapps/opengapps.wiki.git/?

**Comment by DavidBerdik** [comment]
@VincentJoshuaET What about the Open GApps builds available on the website? Do those delete the stock Dialer?

**Comment by VincentJoshuaET** [comment]
Yeah, it seems so. I think the correct keyword is +DialerStock. Or just use Aroma.

**Comment by DavidBerdik** [comment]
How do you use keywords when sideloading it though? I'm not aware of any keywords to change this.

**Comment by curiousrom** [comment]
Why is this major emergency call issue marked as Closed?

The [Advanced Features and Options - gapps-config](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options) file page and it's emergency call WARNING workaround is just lipstick on a pig IMO as just a tiny fraction of Open GApps users will see it and even a smaller % will apply it.

I posted a rant about it on XDA: [Emergency Calls Problem - Open GApps PR Disaster!](https://forum.xda-developers.com/showpost.php?p=78262771&postcount=5756)

**Comment by NicholasBuse** [comment]
@curiousrom , Stop being a jerk. I can copy and paste the same comments everywhere (https://github.com/opengapps/opengapps/issues/618, https://github.com/opengapps/opengapps/issues/672) to get people attention too. It is not helpful.

Here is how you can be helpful: https://github.com/opengapps/opengapps/fork

**Comment by DavidBerdik** [comment]
@NicholasBuse With all due respect, I do not think he was intending to be a jerk. I think he is trying to raise awareness of a very important problem with the OpenGApps project. I think I speak for everyone here when I say that the OpenGApps project is a wonderful piece of work and is essential to the custom ROM community, but the fact that this issue has not been given more attention is really concerning.

This isn't one of those annoying bugs that just gets in the way but is livable. This is a pretty big deal because of the fact that it can quite literally be the difference between life and death. I would love to fork the project and fix it, but unfortunately I currently do not have the time to do so. Not trying to cause GitHub drama, just reiterating that this is a problem that needs solved. 😊

**Comment by curiousrom** [comment]
@jamuir but this gapps-config workaround fixes the broken emergency calls for only a tiny % of Open GApps users.

Looking at the posts above this is the most informative thread about this serious problem & it seems that is would be the place to try to fix the installation script of the Open GApps Packages Mini, Full, Stock & Super.

@DavidBerdik - Thanks, you got the point & are much more diplomatic than I. ;)

**Comment by curiousrom** [comment]
Wow! @SpasilliumNexus just posted here https://github.com/opengapps/opengapps/issues/672#issuecomment-441780202 a link to the merged commit [Prevent stock AOSP Dialer (Phone) from being removed](https://github.com/opengapps/opengapps/pull/696) :)

**Comment by sntxerror** [comment]
Maybe now we can figure out some workarounds? What about complete replacement? Is it possible to include shole google dialer into package?

"Just have them both" sounds like a temporary workaround, but the real problem (broken dialer replacement) is still present.

**Comment by srinivasbollaboyena** [comment]
hi @jamuir ,@SpasilliumNexus,@sntxerror,@NicholasBuse,
Could any help me to this bug where it is actually producing ,
In Aosp dailer source code when I delete a calllog history immedaitely not updating in the callui, when I reopened it is deleting.

**Comment by srinivasbollaboyena** [comment]
> hi @jamuir ,@SpasilliumNexus,@sntxerror,@NicholasBuse, Could any help me to this bug where it is actually producing , In Aosp dailer source code when I delete a calllog history immedaitely not updating in the callui, when I reopened it is deleting.

I have the logs related to this ,
[Uploading log.txt…]()
