### ISSUE TITLE
Broken or possibly missing Android Auto API

### ISSUE THREAD

**Issue by viggy96** [opengapps/opengapps#710]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [X] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**
Android Auto API is either broken or missing causing Android Auto to fail. 

**Reproduction Steps:**

1. Flash OpenGApps
2. Install Android Auto from Play Store
3. Launch Android Auto

**Expected behavior:**
Android Auto starts normally

**Observed behavior:**
Error dialog: "Google Play services doesn't seem to be working at the moment" 
Other Google Play services dependent apps work perfectly. Its isolated to this app

***Logcat of crash***
```
01-04 17:12:11.830  7393  7393 E AndroidRuntime: FATAL EXCEPTION: main
01-04 17:12:11.830  7393  7393 E AndroidRuntime: Process: com.google.android.projection.gearhead:projection, PID: 7393
01-04 17:12:11.830  7393  7393 E AndroidRuntime: java.lang.IllegalStateException: Failed to connect to car service: API_UNAVAILABLE
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at apf.a(SourceFile:120)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at eva.c(SourceFile:15)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at bid.b(SourceFile:405)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at bid.a(SourceFile:434)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at big.a(SourceFile:31)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at cmu.a(SourceFile:9)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.google.android.gms.common.api.internal.GoogleApiClientImpl.g(SourceFile:328)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.google.android.gms.common.api.internal.GoogleApiClientConnecting.i(SourceFile:154)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.google.android.gms.common.api.internal.GoogleApiClientConnecting.St(SourceFile:62)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.google.android.gms.common.api.internal.GoogleApiClientConnecting$a.j(SourceFile:27)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.google.android.gms.common.internal.BaseGmsClient$PostServiceBindingCallback.o(SourceFile:5)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.google.android.gms.common.internal.BaseGmsClient$a.aY(SourceFile:29)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.google.android.gms.common.internal.BaseGmsClient$b.handleMessage(SourceFile:78)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.google.android.gms.libs.punchclock.threads.TracingHandler.dispatchMessage(SourceFile:9)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:164)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6494)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
01-04 17:12:11.830  7393  7393 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by viggy96** [comment]
Related to #707.

**Comment by viggy96** [comment]
Anyone here to answer this issue?

**Comment by viggy96** [comment]
This appears to be fixed in the 10 January 2019 build of OpenGApps.
