### ISSUE TITLE
play store FC with arm64 9.0 pico 20190110 package

### ISSUE THREAD

**Issue by dianlujitao** [opengapps/opengapps#713]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [x] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [x] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [x] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [x] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

[Short description of problem here]

**Reproduction Steps:**

1. Update to 20190110 gapps from previous install
2. Reboot and no longer able to launch play store

**Expected behavior:**

[Describe expected behavior here]
play store launches

**Observed behavior:**
play store FC

[Describe observed behavior here]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**
```
01-11 16:14:29.418 30078 30078 D AndroidRuntime: Shutting down VM
01-11 16:14:29.419 30078 30078 E AndroidRuntime: FATAL EXCEPTION: main
01-11 16:14:29.419 30078 30078 E AndroidRuntime: Process: com.android.vending, PID: 30078
01-11 16:14:29.419 30078 30078 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.finsky.search.RecentSuggestionsProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.android.finsky.search.RecentSuggestionsProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/priv-app/Phonesky/Phonesky.apk"],nativeLibraryDirectories=[/system/priv-app/Phonesky/lib/arm, /system/priv-app/Phonesky/Phonesky.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib, /system/lib, /system/vendor/lib]]
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6445)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5987)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.finsky.search.RecentSuggestionsProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/priv-app/Phonesky/Phonesky.apk"],nativeLibraryDirectories=[/system/priv-app/Phonesky/lib/arm, /system/priv-app/Phonesky/Phonesky.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib, /system/lib, /system/vendor/lib]]
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6429)
01-11 16:14:29.419 30078 30078 E AndroidRuntime: 	... 10 more
```

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by dianlujitao** [comment]
20190108 is the last working build
