### ISSUE TITLE
gapps play store services stop

### ISSUE THREAD

**Issue by julolosvalles26** [opengapps/opengapps#876]
one plus 3 with lineage os 17.1 gapps 22 and 23 August stock and aroma error google services during the assistant or black screen can not be completed or can not start session I have downloaded the same version of July 5 and they do not have any failure it seems that they are going to worse the gapps instead of improving if it continues like this I will end up using the mobile without google with alternative stores thanks for your work I hope it can be fixed

**Comment by osm0sis** [comment]
Still an issue with the current build? Logs please, both of your installation and a logcat from the crash.

**Comment by osm0sis** [comment]
It's been well over a week and you haven't provided anything useful for debugging.

**Comment by julolosvalles26** [comment]
> Ha pasado más de una semana y no ha proporcionado nada útil para la depuración.


and here nothing has been done either the gapps go with each version to the worse I am not going to go crazy uploading things is not my problem enough is that I inform but it works I use other gapps or I change to stock rom that easy

**Comment by osm0sis** [comment]
So, regardless of the fact that it's now 4 months later I'd be happy to reopen this if you provide proper logs and drop the attitude. Nothing can get improved if nobody helps.

**Comment by julolosvalles26** [comment]
![104596437-43493b80-5674-11eb-9af6-a0e72e9430b5](https://user-images.githubusercontent.com/51278544/104618979-a7c4c480-568d-11eb-9429-7310b7f731d7.jpg)

**Comment by julolosvalles26** [comment]
during the first boot it is a one plus 3 with lineage os 17.1 and gapps aroma of 64 bits and that without counting the number of apps that are in English even when selecting Spanish I use the google translator to write this, please in advance if it is not very good And it is about my attitude I apologize but they have already answered me many times in a bad way as I do not understand free software, that I am not special or that I solve it myself and in the end what I do is use other gapps a shame because I consider the Better these I like the aroma package that leaves the best you want and what not and includes gcam thanks for reading everything

**Comment by osm0sis** [comment]
Thank you for giving more information, but please provide the logs I requested, both of your installation and a logcat from the crash.

**Comment by julolosvalles26** [comment]
Thanks to you for answering but the problem is that I am using nickgaps now, I could reinstall the system to be able to do what you ask me but the problem is that I do not know when to do the logcat that you have to put the mobile in adb to It doesn't work but if it is in the middle of boot, how do I access the adb options in the developer or is it from twrp and at what moment I don't know how to make a logcat that can be seen when it fails, so I could never send it

**Comment by osm0sis** [comment]
Well if you do want to try at some point, use the latest Open GApps, install in TWRP and copy /tmp/recovery.log immediately after. Then using root and adb you can do `adb logcat` you'd just need to get to Settings and Developer Options to enable USB Debugging first. If/when you can provide these we can reopen this issue, since not everyone has this issue.

**Comment by julolosvalles26** [comment]
does not start the os can you logcat from twrp? thanks is that it gets stuck in the assistant

I can't open developer

**Comment by osm0sis** [comment]
You would have to modify your boot.img to be adb insecure so you could adb logcat from during boot.

**Comment by julolosvalles26** [comment]
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/5817046/open_gapps_log.txt)
[recovery.log](https://github.com/opengapps/opengapps/files/5817047/recovery.log)
[dmesg.log](https://github.com/opengapps/opengapps/files/5817050/dmesg.log)

**Comment by julolosvalles26** [comment]
I've done what I could, I can't logcat because the system stops and you don't go past the wizard

**Comment by julolosvalles26** [comment]
[logcat.txt](https://github.com/opengapps/opengapps/files/5817126/logcat.txt)

in the end I achieve it, I hope it's worth it, thank you anyway for helping me

**Comment by julolosvalles26** [comment]
is this still open? nobody discovered anything

**Comment by osm0sis** [comment]
You watched me reopen it for you, now you'll have to be patient, since the Open GApps team is basically 2 people right now.

**Comment by dtrunk90** [comment]
Not sure if this is exactly the same issue and thus related to but I faced the same that google play services stopped working on a samsung tablet with LineageOS 16 (Android 9) installed. Play services: 21.36.14
```
10-01 19:08:16.304  7874  7874 E AndroidRuntime: FATAL EXCEPTION: main
10-01 19:08:16.304  7874  7874 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 7874
10-01 19:08:16.304  7874  7874 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method ()B in class B or its super classes (declaration of 'byte' appears in generated class)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at byte.(:com.google.android.gms@213614028@21.36.14 (100400-395708125):0)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at qko.<clinit>(:com.google.android.gms@213614028@21.36.14 (100400-395708125):1)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5891)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-01 19:08:16.304  7874  7874 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-01 19:08:16.468  7852  7852 E cr_CompositorSurfaceMgr: Transitioning to surface with format : -1
10-01 19:08:16.515  2612  3201 E BufferQueueProducer: [com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher#0] disconnect: not connected (req=1)
10-01 19:08:16.876  7852  7925 E chromium: [ERROR:chrome_browser_main_extra_parts_metrics.cc(228)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
10-01 19:08:16.876  7852  7925 E chromium: [ERROR:chrome_browser_main_extra_parts_metrics.cc(231)] crbug.com/1216328: Checking Bluetooth availability ended.
10-01 19:08:16.876  7852  7925 E chromium: [ERROR:chrome_browser_main_extra_parts_metrics.cc(234)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
10-01 19:08:16.876  7852  7925 E chromium: [ERROR:chrome_browser_main_extra_parts_metrics.cc(238)] crbug.com/1216328: Checking default browser status ended.
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: Inflation exception.
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: android.view.InflateException: Binary XML file line #26: Binary XML file line #11: Error inflating class <unknown>
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class <unknown>
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: Caused by: java.lang.reflect.InvocationTargetException
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:963)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at iO1.a(chromium-Monochrome.aab-stable-460606123:3)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at tC4.b(chromium-Monochrome.aab-stable-460606123:7)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at et0.run(chromium-Monochrome.aab-stable-460606123:4)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at kS.run(chromium-Monochrome.aab-stable-460606123:10)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.os.MessageQueue.next(MessageQueue.java:326)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.os.Looper.loop(Looper.java:160)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: Caused by: java.lang.IllegalArgumentException: ChromeColors requires a value for the com.android.chrome:attr/0_resource_name_obfuscated attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at y12.c(chromium-Monochrome.aab-stable-460606123:5)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at i00.b(chromium-Monochrome.aab-stable-460606123:4)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at org.chromium.chrome.browser.compositor.CompositorView.g(chromium-Monochrome.aab-stable-460606123:5)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at org.chromium.chrome.browser.compositor.CompositorView.<init>(chromium-Monochrome.aab-stable-460606123:5)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	at org.chromium.chrome.browser.compositor.CompositorViewHolder.<init>(chromium-Monochrome.aab-stable-460606123:15)
10-01 19:08:16.946  7852  7852 E cr_WarmupManager: 	... 23 more
10-01 19:08:17.076  7852  7900 E ion     : ioctl c0044901 failed with code -1: Invalid argument
10-01 19:08:17.093  7852  7852 E cr_CompositorSurfaceMgr: Transitioning to surface with format : -1
10-01 19:08:17.095  7852  7852 E cr_CompositorSurfaceMgr: surfaceCreated format : 0
10-01 19:08:17.596  7937  7955 E ion     : ioctl c0044901 failed with code -1: Invalid argument
```

**Comment by tenzap** [comment]
I'm also facing crashes of Play Store once it is updated and after a reboot.
To reproduce, update playstore (eg from 28.7 to 28.8), then reboot. Now it will crash.

**Comment by osm0sis** [comment]
Sounds like something Google might have to resolve?
