### ISSUE TITLE
Device Health Services crash on startup

### ISSUE THREAD

**Issue by rapperskull** [opengapps/opengapps#886]
Every time I reboot my device Device Health Services crashes. Device is Xiaomi Mi Mix 2S, ROM is ArrowOS 10.0. This is the crash log:

`
time: 1601663451254
msg: java.lang.IllegalStateException: Turbo installed on a device without a default curve.
stacktrace: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: Turbo installed on a device without a default curve.
	at bnp.a(PG:7)
	at bnp.b(PG:46)
	at bnu.<init>(PG:1)
	at com.google.android.libraries.smartbattery.brightness.library.UpdateOfflineModelJob.a(PG:231)
	at bne.doInBackground(Unknown Source:146)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
`

As I understand from the log the problem is with the device itself. Maybe the ROM or the vendor partition is missing something? But I can't find any information on what a ROM should include to make Turbo work properly, so maybe this could be, if not a compatibility issue, at least a documentation issue.

**Comment by osm0sis** [comment]
Not much to be done here unfortunately.
