### ISSUE TITLE
PackageManagerService

### ISSUE THREAD

**Issue by Gianmariai** [opengapps/opengapps#899]
Hello All,
after AOSP compilation, device remain stuck on boot with this message repeateed again and againt:

2000-01-01 01:22:40.810 5560-5560/system_process E/AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
    java.lang.RuntimeException: There must be exactly one installer; found [ResolveInfo{5811160 com.android.packageinstaller/.InstallStart m=0x608000}, ResolveInfo{b7fd619 com.google.android.packageinstaller/com.android.packageinstaller.InstallStart m=0x608000}]
        at com.android.server.pm.PackageManagerService.getRequiredInstallerLPr(PackageManagerService.java:3740)
        at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:3280)
        at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2295)
        at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:736)
        at com.android.server.SystemServer.run(SystemServer.java:510)
        at com.android.server.SystemServer.main(SystemServer.java:349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:968)

Maybe i'm doing something wrong? Do I have to customize some mk file?

REgards,
Gianmaria

**Comment by osm0sis** [comment]
If this is an AOSP_build bug then it should be over there, not here.
